# Packages and Library

install.packages("tidyverse")
install.packages("readxl")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("RColorBrewer")
install.packages("plotrix")
install.packages("ggpubr")
install.packages("ggthemes")
install.packages("maps")
install.packages("tidyverse")
install.packages("forcats")
library(forcats)
library(tidyverse)
library(maps)
library(ggthemes)
library(ggpubr)
library(plotrix)
library(RColorBrewer)
library(ggplot2)
library(tidyverse)
library(readxl)
library(dplyr)

# Mean , Median , Mode , Range and Standard Deviation

sales_mean <- round(mean(ss$Sales),2)
sales_median <- round(median(ss$Sales),2)
sales_sd <- round(sd(ss$Sales),2)
sales_range <- round(max(ss$Sales)- min(ss$Sales), 2)


net_mean <- round(mean(ss$`Net sales`),2)
net_median <- round(median(ss$`Net sales`),2)
net_sd <- round(sd(ss$`Net sales`),2)
net_range <- round(max(ss$`Net sales`)-min(ss$`Net sales`),2)


loss_mean <- round(mean(ss$Loss),2)
loss_median <- round(median(ss$Loss),2)
loss_range <- round(max(ss$Loss)-min(ss$Loss),2)
loss_sd <- round(sd(ss$Loss),2)


profit_mean <- round(mean(ss$Profit),2)
profit_median <- round(median(ss$Profit),2)
profit_range <- round(max(ss$Profit)-min(ss$Profit),2)
profit_sd <- round(sd(ss$Profit),2)


Variable <- c("SALES", "NET SALES", "LOSS", "PROFIT")
Mean <- c(sales_mean, net_mean, loss_mean, profit_mean)
Median <- c(sales_median, net_median, loss_median, profit_median)
Range <- c(sales_range, net_range, loss_range, profit_range)
SD <- c(sales_sd, net_sd, loss_sd, profit_sd)

stats = data.frame(Variable, Mean, Median, Range, SD, stringsAsFactors=FALSE)
knitr::kable(stats)




# Pie-Chart of All Categories


pie(table(ss$Category),
labels = table(ss$Category),
col = c("mediumpurple4","darkorchid2","mediumpurple1"),
main = "Number of Categories")
legend("topleft", legend = paste(unique(ss$Category)),
       fill = c("mediumpurple4","darkorchid2","mediumpurple1"))

region_profit <- tapply(ss$Sales, ss$Category, sum)
dotchart(region_profit, pch = 24, bg="blue", cex=1.3, xlab = "profit", main = "Profit Made by Each Category")

# Box-Plot 

ss %>%
ggplot(aes(Category, Sales))+
  geom_boxplot(outlier.colour="black", outlier.shape=16,
               outlier.size=2, notch=FALSE)+
  scale_y_discrete(limits=c(0, 20000))


# Statistical Test (Anova)

adata <- ss %>% 
  filter(Category %in% c("Furniture", "Office Supplies")) %>%
  select(Category, Sales)

  

adata %>%
  aov(Sales ~ Category, data = .,) %>%
  summary()

adata %>%
  aov(Sales ~ Category, data = .,) %>%
  TukeyHSD() 
  


# Bar-Chart of Orders in Different Regions

barplot(table(ss$Region),
        main = "Orders in Different Regions",
        ylab = "Frequency",
        col = brewer.pal(5, "YlGnBu"))


# Profit Chart Across Different Regions

ggplot(ss, aes(x = Region, y = Profit)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title="Profits across different regions in Europe")+
  theme_par() +
  theme(legend.position = "top") 

# Statistical Test (Two Sided T-test)

ss %>% 
  filter(Region %in% c("Central", "South")) %>%
  t.test(Sales ~ Region, data = ., alternative = "two.sided")


# Bar-Chart for Numbers of Days it Takes to Ship Products 


ss$`Order Date`= as.Date(ss$`Order Date`, format="%d/%m/%y")
ss$`Ship Date`= as.Date(ss$`Ship Date`, format="%d/%m/%y")
ss$days=ss$`Ship Date`-ss$`Order Date`
days = table(ss$days)
barplot(days,
        ylim = c(0,3500),
            main = "Number of days it takes to ship a product",
            xlab = "Days",
            ylab = "Frequency",
            col = c("darkslategray1","deepskyblue","dodgerblue2"))


# Number of Orders in Each Day

ss$weekday = format(ss$`Order Date`,"%a")
weekday = factor(ss$weekday, levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
x = barplot(table(weekday), 
            ylim = c(0,2700),
            main = "On which days do customers create most orders?", 
            col = c(terrain.colors(7)),
            xlab = "Day",
            ylab = "Number of orders")
text(y = table(weekday), 
     x, 
     table(weekday), 
     cex=0.9, 
     pos = 1)

# Profit Generated On Each Day

week_profit = tapply(ss$Profit, weekday, sum)
dotchart(week_profit, pch = 22, bg = "purple1", cex = 1.2, 
         xlab="Median value of profits",
         main = "What is the profit \nfor each day of the week?")




# Pie-Chart to Show Number of Orders by Customer Segment

pie(table(ss$Segment),
    labels = table(ss$Segment), 
    col = c("paleturquoise1","steelblue1","lightslateblue"),
    main = "Number of orders by customer segment")

legend("topleft", legend = paste(unique(ss$Segment)), 
       fill = c("paleturquoise1","steelblue1","lightslateblue"))


# Sales Generated by each Segment

table3 <- aggregate( Sales ~ Segment, ss, sum)
knitr::kable(table3)
view(table3)

# Statistical Test (Chi-sq. Independence Test) 

ctest <- table(ss$Sales, ss$Segment)
ctest
chisq.test(ctest)

# Region Category and Sales Table

table1 <- ss %>% 
  select(Region,Category,Sales) %>%
group_by(Region, Category) %>%
  summarise(sum(Sales))
  knitr::kable(table1)
  View(table1)
  
# Bar-Chart of Category Sold in each Region and Profit Generated by each   
  
 ss %>% ggplot(aes(x=Region,
                    y=Sales,
                    fill=Category))+
    geom_col(width = 0.6, position = position_dodge(0.6))+
labs(x="Regions",
     y="Profit") +
    theme_stata() +
    scale_fill_stata()

 


  
  

  